### PR TITLE
Bump cljsjs/antd to 3.2.0-0

### PR DESCRIPTION
**Pull request by Baspar**
Bump cljsjs/antd to 3.2.0-0

### CODE REVIEW

**Comment by bzg** [comment]
:+1:

**Comment by bzg** [comment]
Thanks for this PR! I hope @priornix has some free time at hand to handle this. (I know being a free software maintainer can be challenging, so please don't read this as me being pushy.)

**Comment by simplect** [comment]
I believe there are some additional changes which need to be done. A lot of forks did this correctly. For example: https://github.com/Eeleven/antizer/commit/2ddc8ee8220487ff467a677440954f8930e9455b I personally use this fork: https://clojars.org/sooheon/antizer

**Comment by Baspar** [comment]
It looks too easy to be true :p 
I'll update the API and thing that are missing and come back

**Comment by priornix** [comment]
Apologies for not following up on this, but as @Baspar said it is almost too easy to upgrade this. Thank you @sooheon and @eeleven for doing this. Anyway, this library has been updated to antd 2.7.1. Enjoy!

**Pull request closed without merging**
