### PR TITLE
upgrade antd to 3.12.0

### PR DESCRIPTION
**Pull request by kevindragon**
upgrade antd to 3.12.0

### CODE REVIEW

**Comment by deoqc** [comment]
Missing other component: [PageHeader](https://ant.design/components/page-header/)

**Comment by ertugrulcetin** [comment]
@priornix please accept this PR :)

**Comment by ertugrulcetin** [comment]
@kevindragon @leontalbot @deoqc there you go it's "3.19.0" -> [antizer-latest "0.1.0"]

**Comment by priornix** [comment]
Thanks @kevindragon @ertugrulcetin @deoqc @leontalbot This has been merged, I've also updated to the latest 3.x version as well.

**Pull request closed without merging**
