### PR TITLE
Bump versions, use 3.3.0-0

### PR DESCRIPTION
**Pull request by piotr-yuxuan**

### CODE REVIEW

**Comment by rune-brinckmeyer** [comment]
Any plans/timeline wrt accept this pull-request?

**Comment by piotr-yuxuan** [comment]
Anything I can do to help the process of getting this merged?

**Comment by yanlobkarev** [comment]
...ping
Any updates?

**Comment by yanlobkarev** [comment]
@piotr-yuxuan 
Firstly, must say thanks for You devotion and work!
Secondly, I tried out your master branch and had an issue with `(ant/list)`:

> Warning: React.createElement(...): Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored. react.inc.js

for code:

```(ns blackbooks.app
  (:require [antizer.rum :as ant]
            [goog.dom :as gdom]
            [rum.core :as rum]
  ))

(enable-console-print!)

(rum/defc app < rum/static
  []
  (ant/list
    {:item-layout "horizontal"
    :grid {:gutter 16 :column 4}
    :data-source (repeat 4 {:title "title"})
    :render-item (fn [item]
                   (let [{:keys [title]} (js->clj item :keywordize-keys true)]
                     (ant/list-item
                       (ant/card {:title title}
                                 "Card content"))))
    }))

(rum/mount (app) (gdom/getElement "app"))
```
However everything had been displayed properly:


Should I open issue?

**Comment by piotr-yuxuan** [comment]
I've just seen it. Let's see what I can do.

**Comment by priornix** [comment]
@yanlobkarev I have tried your example and it create any issues with antd verison 3.7.1. Perhaps you should try upgrading to [0.3.0](https://github.com/priornix/antizer/tree/0.3.0). Otherwise, please open a new ticket if you are still having problems.

**Comment by priornix** [comment]
@piotr-yuxuan Can we close this?

**Pull request closed without merging**
